name: Install NSIS plugins

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: NSIS plugins
        shell: bash
        run: ./.github/workflows/actions/installnsisplugins.sh
