name: Install NSIS plugins

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
          fetch-depth: 1
      - name: NSIS plugins
        shell: bash
        run: ./.github/workflows/actions/download_plugins.py
